### ISSUE TITLE
Unable to set multiple independant switches

### ISSUE THREAD

**Issue by Nepomucene** [iSteve-O/homebridge-multiswitcheroo#7]
I have 2 bikes, each with the same alarm from the same vendor.
I can use MultiSwitcheroo to poll the status of one bike, and arm/disarm its alarm.

But I cannot manage both.
Is it possible to set 2 independant accessories (with different status/on/off urls)?

**Comment by iSteve-O** [comment]
Yes, you can either add another accessory in the config UI Plugin settings by scrolling under your current accessory and tapping "add accessory", or you could copy and paste the raw config of the first and edit the few details unique to the 2nd. 

You can even expose both accessories over the same child bridge, if you use child bridges. Just put the same bridge username and port for both "accessories". 

I recommend using this plugin in a child bridge. It isolates the process so it won't slow down any others or the main Homebridge, and it has the added benefit of being able to just restart the child bridge when you make changes.

Since you are defining a 2nd accessory, you will have to add the username and port to the config manually for the 2nd accessory if you wish to expose both on the same child bridge. Otherwise each will just be on its own child bridge (which has its own benefits, keeping them separated). 

If you don't use child bridges both switches will just be exposed on the main Homebridge. 

Sorry if that was confusing. I read it after posting and it seems weird.

**Comment by Nepomucene** [comment]
Got it, many thanks!
